version: 0.1

phases:
  pre_build:

     commands:

       - npm install

       - npm test

  build:
    commands:
      -npm run webpack
artifacts:
   files:
     -index.html
     -favicon.ico
     -Shivali_Singh_Website.pdf
     -styles/main.css
     -images/*
     -dist/bundle.js
